<a href="https://colab.research.google.com/github/cakewaterrr/REU-Summer-2022/blob/main/Pytorch_(NN%3F)_Linear_Regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch
import torch.nn as nn
import numpy as np
import torch.nn.functional as F
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [7]:
# Inputs (Temperature, Rainfall, Humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37], [69, 96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37],
                   [69, 96, 70], [73, 67, 43], [91, 88, 64],
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]],
                  dtype='float32')

# Targets (Apples, Oranges)
targets = np.array([[56, 70], [81, 101], [119, 133],
                    [22, 37], [103, 119], [56, 70],
                    [81, 101], [119, 133], [22, 37],
                    [103, 119], [56, 70], [81, 101],
                   [119, 133], [22, 37], [103, 119]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [8]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [9]:
# Define dataloader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True )

In [10]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [119., 133.],
        [103., 119.]])


In [11]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0336,  0.3368, -0.2272],
        [ 0.2138, -0.3490, -0.0608]], requires_grad=True)
Parameter containing:
tensor([-0.0296, -0.1227], requires_grad=True)


In [12]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0336,  0.3368, -0.2272],
         [ 0.2138, -0.3490, -0.0608]], requires_grad=True),
 Parameter containing:
 tensor([-0.0296, -0.1227], requires_grad=True)]

In [14]:
# Generating predictions
preds = model(inputs)
preds

tensor([[ 15.2207, -10.5156],
        [ 18.1278, -15.2735],
        [ 34.8517, -31.8192],
        [  9.4727,   4.4249],
        [ 18.7212, -23.1332],
        [ 15.2207, -10.5156],
        [ 18.1278, -15.2735],
        [ 34.8517, -31.8192],
        [  9.4727,   4.4249],
        [ 18.7212, -23.1332],
        [ 15.2207, -10.5156],
        [ 18.1278, -15.2735],
        [ 34.8517, -31.8192],
        [  9.4727,   4.4249],
        [ 18.7212, -23.1332]], grad_fn=<AddmmBackward0>)

In [17]:
# Define loss function
loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
loss

tensor(8838.7295, grad_fn=<MseLossBackward0>)

In [18]:
# Define Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [19]:
# Training the model

def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    # Train with batches of data
    for xb, yb in train_dl:
      # Generate prediciton
      pred = model(xb)
      # Calculate Loss
      loss = loss_fn(pred, yb)
      # Compute Gradients
      loss.backward()
      # Update Parameters Using Gradients (with statement)
      opt.step()
      # Reset Gradients to Zero
      opt.zero_grad()

    # Print Progress
    if (epoch+1) % 10 == 0:
      print("Epoch [{}/{}], Loss: {:.4f}".format(epoch+1, num_epochs,loss.item()))


In [20]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 822.3975
Epoch [20/100], Loss: 276.2852
Epoch [30/100], Loss: 79.4109
Epoch [40/100], Loss: 65.7780
Epoch [50/100], Loss: 170.7250
Epoch [60/100], Loss: 7.0810
Epoch [70/100], Loss: 8.4119
Epoch [80/100], Loss: 65.8302
Epoch [90/100], Loss: 26.0233
Epoch [100/100], Loss: 49.8058


In [21]:
preds = model(inputs)
preds

tensor([[ 58.6189,  72.1948],
        [ 79.2598,  98.9512],
        [124.0754, 134.8058],
        [ 28.3567,  47.0225],
        [ 92.4685, 110.2133],
        [ 58.6189,  72.1948],
        [ 79.2598,  98.9512],
        [124.0754, 134.8058],
        [ 28.3567,  47.0225],
        [ 92.4685, 110.2133],
        [ 58.6189,  72.1948],
        [ 79.2598,  98.9512],
        [124.0754, 134.8058],
        [ 28.3567,  47.0225],
        [ 92.4685, 110.2133]], grad_fn=<AddmmBackward0>)

In [22]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])